crds:
  enabled: true

ingressShim:
  defaultIssuerName: k3d-play-issuer
  defaultIssuerKind: ClusterIssuer

extraObjects:
  - |-
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: selfsigned-issuer
    spec:
      selfSigned: {}

  - |-
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: k3d-play-ca
    spec:
      isCA: true
      commonName: K3d Play CA 
      secretName: root-secret
      privateKey:
        algorithm: ECDSA
        size: 256
      issuerRef:
        name: selfsigned-issuer
        kind: ClusterIssuer
        group: cert-manager.io

  - |-
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: k3d-play-issuer
    spec:
      ca:
        secretName: root-secret

  - |-
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: traefik-default-cert
      namespace: kube-system
    spec:
      commonName: traefik
      secretName: traefik-default-tls
      dnsNames:
        - "localhost"
        - "*.localhost"
        - "*.play.localhost"
      issuerRef:
        name: k3d-play-issuer
        kind: ClusterIssuer
        group: cert-manager.io
