apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: play
servers: 1
subnet: auto
ports:
- port: '10080:80'
  nodeFilters:
  - loadbalancer
- port: '10443:443'
  nodeFilters:
  - loadbalancer
options:
  k3s:
    extraArgs:
    - arg: '--kubelet-arg=feature-gates=KubeletInUserNamespace=true'
      nodeFilters:
      - server:*
      - agent:*
    - arg: '--disable=traefik'
      nodeFilters:
      - server:*
